variables:
  # https://setuptools-git-versioning.readthedocs.io/en/stable/ci.html
  GIT_DEPTH: 0
  VERSION_REGEX: /^v\d+\.\d+\.\d+.*$/

stages:
  - test
  - build

buf-lint:
  image: registry.fiblab.net/general/dev:latest
  stage: test
  script:
    - buf lint

release-pypi:
  # 以开发镜像作为执行环境
  image: registry.fiblab.net/general/dev:latest
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_REGEX
  script:
    - pip3 install build setuptools-git-versioning -U
    - python3 -m build
    - |
      TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token \
      python3 -m twine upload --repository-url \
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

