// @generated by protoc-gen-es v1.10.0
// @generated from file city/water/interaction/v1/water_service.proto (package city.water.interaction.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum city.water.interaction.v1.WaterFacilityType
 */
export const WaterFacilityType = /*@__PURE__*/ proto3.makeEnum(
  "city.water.interaction.v1.WaterFacilityType",
  [
    {no: 0, name: "WATER_FACILITY_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "WATER_FACILITY_TYPE_SUPPLY", localName: "SUPPLY"},
    {no: 2, name: "WATER_FACILITY_TYPE_DRAINAGE", localName: "DRAINAGE"},
  ],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpPowerStatusRequest
 */
export const SetPumpPowerStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpPowerStatusRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "type", kind: "enum", T: proto3.getEnumType(WaterFacilityType) },
  ],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpPowerStatusResponse
 */
export const SetPumpPowerStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpPowerStatusResponse",
  [],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpNetworkStatusRequest
 */
export const SetPumpNetworkStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpNetworkStatusRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "type", kind: "enum", T: proto3.getEnumType(WaterFacilityType) },
  ],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpNetworkStatusResponse
 */
export const SetPumpNetworkStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpNetworkStatusResponse",
  [],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpStatusRequest
 */
export const SetPumpStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpStatusRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "type", kind: "enum", T: proto3.getEnumType(WaterFacilityType) },
  ],
);

/**
 * @generated from message city.water.interaction.v1.SetPumpStatusResponse
 */
export const SetPumpStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.SetPumpStatusResponse",
  [],
);

/**
 * @generated from message city.water.interaction.v1.GetPumpStatusRequest
 */
export const GetPumpStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetPumpStatusRequest",
  () => [
    { no: 1, name: "flag", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message city.water.interaction.v1.GetPumpStatusResponse
 */
export const GetPumpStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetPumpStatusResponse",
  () => [
    { no: 1, name: "pump_status", kind: "map", K: 5 /* ScalarType.INT32 */, V: {kind: "scalar", T: 5 /* ScalarType.INT32 */} },
  ],
);

/**
 * @generated from message city.water.interaction.v1.GetNoWaterAOIRequest
 */
export const GetNoWaterAOIRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetNoWaterAOIRequest",
  () => [
    { no: 1, name: "flag", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message city.water.interaction.v1.GetNoWaterAOIResponse
 */
export const GetNoWaterAOIResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetNoWaterAOIResponse",
  () => [
    { no: 1, name: "aoi", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
  ],
);

/**
 * @generated from message city.water.interaction.v1.GetRuinInfoRequest
 */
export const GetRuinInfoRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetRuinInfoRequest",
  [],
);

/**
 * @generated from message city.water.interaction.v1.RuinInfo
 */
export const RuinInfo = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.RuinInfo",
  () => [
    { no: 1, name: "num", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "ratio", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message city.water.interaction.v1.GetRuinInfoResponse
 */
export const GetRuinInfoResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.water.interaction.v1.GetRuinInfoResponse",
  () => [
    { no: 1, name: "one", kind: "message", T: RuinInfo },
    { no: 2, name: "two", kind: "message", T: RuinInfo },
    { no: 3, name: "three", kind: "message", T: RuinInfo },
  ],
);

