// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: city/water/output/v1/output.proto

package outputv1

import (
	v2 "git.fiblab.net/sim/protos/go/city/geo/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkType int32

const (
	LinkType_LINK_TYPE_UNSPECIFIED LinkType = 0
	LinkType_LINK_TYPE_PIPE        LinkType = 1
	LinkType_LINK_TYPE_PUMP        LinkType = 2
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_UNSPECIFIED",
		1: "LINK_TYPE_PIPE",
		2: "LINK_TYPE_PUMP",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNSPECIFIED": 0,
		"LINK_TYPE_PIPE":        1,
		"LINK_TYPE_PUMP":        2,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_city_water_output_v1_output_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_city_water_output_v1_output_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{0}
}

// 宏观道路水深
type Road struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Depth float64 `protobuf:"fixed64,2,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *Road) Reset() {
	*x = Road{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Road) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Road) ProtoMessage() {}

func (x *Road) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Road.ProtoReflect.Descriptor instead.
func (*Road) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{0}
}

func (x *Road) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Road) GetDepth() float64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// 微观水深点
type RoadFlood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *v2.LongLatPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Depth    float64             `protobuf:"fixed64,2,opt,name=depth,proto3" json:"depth,omitempty"`
}

func (x *RoadFlood) Reset() {
	*x = RoadFlood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoadFlood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadFlood) ProtoMessage() {}

func (x *RoadFlood) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadFlood.ProtoReflect.Descriptor instead.
func (*RoadFlood) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{1}
}

func (x *RoadFlood) GetPosition() *v2.LongLatPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RoadFlood) GetDepth() float64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type DetailedRoad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Depths []*RoadFlood `protobuf:"bytes,2,rep,name=depths,proto3" json:"depths,omitempty"`
}

func (x *DetailedRoad) Reset() {
	*x = DetailedRoad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailedRoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedRoad) ProtoMessage() {}

func (x *DetailedRoad) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedRoad.ProtoReflect.Descriptor instead.
func (*DetailedRoad) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{2}
}

func (x *DetailedRoad) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetailedRoad) GetDepths() []*RoadFlood {
	if x != nil {
		return x.Depths
	}
	return nil
}

// 节点状态
type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node分两种, junction和outfall, outfall的id将以"_out"后缀
	// 但输出不关心NodeType, 不需用type字段显示记录
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 水头，单位：米
	Head float64 `protobuf:"fixed64,2,opt,name=head,proto3" json:"head,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetHead() float64 {
	if x != nil {
		return x.Head
	}
	return 0
}

// 边的状态
type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type为LINK_TYPE_PUMP的id将以"Pump_"前缀
	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type LinkType `protobuf:"varint,2,opt,name=type,proto3,enum=city.water.output.v1.LinkType" json:"type,omitempty"`
	// 流量
	// 排水网，单位：m3/s
	// 供水网，单位：L/s
	Flow float64 `protobuf:"fixed64,3,opt,name=flow,proto3" json:"flow,omitempty"`
	Ok   bool    `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{4}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetType() LinkType {
	if x != nil {
		return x.Type
	}
	return LinkType_LINK_TYPE_UNSPECIFIED
}

func (x *Link) GetFlow() float64 {
	if x != nil {
		return x.Flow
	}
	return 0
}

func (x *Link) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Aoi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UnsatisfiedNum   int32   `protobuf:"varint,2,opt,name=unsatisfied_num,json=unsatisfiedNum,proto3" json:"unsatisfied_num,omitempty"`        // AOI用水需求不满足人数
	UnsatisfiedRatio float64 `protobuf:"fixed64,3,opt,name=unsatisfied_ratio,json=unsatisfiedRatio,proto3" json:"unsatisfied_ratio,omitempty"` // AOI用水需求不满足比例
	Demand           float64 `protobuf:"fixed64,4,opt,name=demand,proto3" json:"demand,omitempty"`                                             // AOI用水需求量 m3/s
	Supply           float64 `protobuf:"fixed64,5,opt,name=supply,proto3" json:"supply,omitempty"`                                             // AOI供水量 m3/s
}

func (x *Aoi) Reset() {
	*x = Aoi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aoi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aoi) ProtoMessage() {}

func (x *Aoi) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aoi.ProtoReflect.Descriptor instead.
func (*Aoi) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{5}
}

func (x *Aoi) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Aoi) GetUnsatisfiedNum() int32 {
	if x != nil {
		return x.UnsatisfiedNum
	}
	return 0
}

func (x *Aoi) GetUnsatisfiedRatio() float64 {
	if x != nil {
		return x.UnsatisfiedRatio
	}
	return 0
}

func (x *Aoi) GetDemand() float64 {
	if x != nil {
		return x.Demand
	}
	return 0
}

func (x *Aoi) GetSupply() float64 {
	if x != nil {
		return x.Supply
	}
	return 0
}

// 排水基础信息
type DrainageBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AveragePower    float64 `protobuf:"fixed64,1,opt,name=average_power,json=averagePower,proto3" json:"average_power,omitempty"`          // 排水泵平均功率 kW
	UndrainedVolume float64 `protobuf:"fixed64,2,opt,name=undrained_volume,json=undrainedVolume,proto3" json:"undrained_volume,omitempty"` // 待排水量 m3
	DrainedVolume   float64 `protobuf:"fixed64,3,opt,name=drained_volume,json=drainedVolume,proto3" json:"drained_volume,omitempty"`       // 已排水量 m3
	AverageFlow     float64 `protobuf:"fixed64,4,opt,name=average_flow,json=averageFlow,proto3" json:"average_flow,omitempty"`             // 平均流量 m3/s
	FloodedVolume   float64 `protobuf:"fixed64,5,opt,name=flooded_volume,json=floodedVolume,proto3" json:"flooded_volume,omitempty"`       // 积水水量 m3
}

func (x *DrainageBasicInfo) Reset() {
	*x = DrainageBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrainageBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainageBasicInfo) ProtoMessage() {}

func (x *DrainageBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainageBasicInfo.ProtoReflect.Descriptor instead.
func (*DrainageBasicInfo) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{6}
}

func (x *DrainageBasicInfo) GetAveragePower() float64 {
	if x != nil {
		return x.AveragePower
	}
	return 0
}

func (x *DrainageBasicInfo) GetUndrainedVolume() float64 {
	if x != nil {
		return x.UndrainedVolume
	}
	return 0
}

func (x *DrainageBasicInfo) GetDrainedVolume() float64 {
	if x != nil {
		return x.DrainedVolume
	}
	return 0
}

func (x *DrainageBasicInfo) GetAverageFlow() float64 {
	if x != nil {
		return x.AverageFlow
	}
	return 0
}

func (x *DrainageBasicInfo) GetFloodedVolume() float64 {
	if x != nil {
		return x.FloodedVolume
	}
	return 0
}

// 供水基础信息
type SupplyBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AveragePower float64 `protobuf:"fixed64,1,opt,name=average_power,json=averagePower,proto3" json:"average_power,omitempty"` // 供水泵平均功率 kW
	AverageFlow  float64 `protobuf:"fixed64,2,opt,name=average_flow,json=averageFlow,proto3" json:"average_flow,omitempty"`    // 平均流量 m3/s
}

func (x *SupplyBasicInfo) Reset() {
	*x = SupplyBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyBasicInfo) ProtoMessage() {}

func (x *SupplyBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyBasicInfo.ProtoReflect.Descriptor instead.
func (*SupplyBasicInfo) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{7}
}

func (x *SupplyBasicInfo) GetAveragePower() float64 {
	if x != nil {
		return x.AveragePower
	}
	return 0
}

func (x *SupplyBasicInfo) GetAverageFlow() float64 {
	if x != nil {
		return x.AverageFlow
	}
	return 0
}

// 供水需求及满足情况
type SupplyDemandStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonsDemand           float64 `protobuf:"fixed64,1,opt,name=persons_demand,json=personsDemand,proto3" json:"persons_demand,omitempty"`                                 // 居民总用水需求 m3/s
	UnsatisfiedPersons      int32   `protobuf:"varint,2,opt,name=unsatisfied_persons,json=unsatisfiedPersons,proto3" json:"unsatisfied_persons,omitempty"`                   // 居民需求不满足人数
	UnsatisfiedPersonsRatio float64 `protobuf:"fixed64,3,opt,name=unsatisfied_persons_ratio,json=unsatisfiedPersonsRatio,proto3" json:"unsatisfied_persons_ratio,omitempty"` // 居民需求不满足比例
	AoisDemand              float64 `protobuf:"fixed64,4,opt,name=aois_demand,json=aoisDemand,proto3" json:"aois_demand,omitempty"`                                          // AOI总用水需求 m3/s
	UnsatisfiedAois         int32   `protobuf:"varint,5,opt,name=unsatisfied_aois,json=unsatisfiedAois,proto3" json:"unsatisfied_aois,omitempty"`                            // AOI需求不满足个数
	UnsatisfiedAoisRatio    float64 `protobuf:"fixed64,6,opt,name=unsatisfied_aois_ratio,json=unsatisfiedAoisRatio,proto3" json:"unsatisfied_aois_ratio,omitempty"`          // AOI需求不满足比例
}

func (x *SupplyDemandStatistics) Reset() {
	*x = SupplyDemandStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyDemandStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyDemandStatistics) ProtoMessage() {}

func (x *SupplyDemandStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyDemandStatistics.ProtoReflect.Descriptor instead.
func (*SupplyDemandStatistics) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{8}
}

func (x *SupplyDemandStatistics) GetPersonsDemand() float64 {
	if x != nil {
		return x.PersonsDemand
	}
	return 0
}

func (x *SupplyDemandStatistics) GetUnsatisfiedPersons() int32 {
	if x != nil {
		return x.UnsatisfiedPersons
	}
	return 0
}

func (x *SupplyDemandStatistics) GetUnsatisfiedPersonsRatio() float64 {
	if x != nil {
		return x.UnsatisfiedPersonsRatio
	}
	return 0
}

func (x *SupplyDemandStatistics) GetAoisDemand() float64 {
	if x != nil {
		return x.AoisDemand
	}
	return 0
}

func (x *SupplyDemandStatistics) GetUnsatisfiedAois() int32 {
	if x != nil {
		return x.UnsatisfiedAois
	}
	return 0
}

func (x *SupplyDemandStatistics) GetUnsatisfiedAoisRatio() float64 {
	if x != nil {
		return x.UnsatisfiedAoisRatio
	}
	return 0
}

// 水泵损坏情况
type FailureStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FailureNum   int32   `protobuf:"varint,1,opt,name=failure_num,json=failureNum,proto3" json:"failure_num,omitempty"`
	NormalNum    int32   `protobuf:"varint,2,opt,name=normal_num,json=normalNum,proto3" json:"normal_num,omitempty"`
	FailureRatio float64 `protobuf:"fixed64,3,opt,name=failure_ratio,json=failureRatio,proto3" json:"failure_ratio,omitempty"`
}

func (x *FailureStatistics) Reset() {
	*x = FailureStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailureStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureStatistics) ProtoMessage() {}

func (x *FailureStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureStatistics.ProtoReflect.Descriptor instead.
func (*FailureStatistics) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{9}
}

func (x *FailureStatistics) GetFailureNum() int32 {
	if x != nil {
		return x.FailureNum
	}
	return 0
}

func (x *FailureStatistics) GetNormalNum() int32 {
	if x != nil {
		return x.NormalNum
	}
	return 0
}

func (x *FailureStatistics) GetFailureRatio() float64 {
	if x != nil {
		return x.FailureRatio
	}
	return 0
}

// 排水指标
type DrainageMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrainageBasicInfo *DrainageBasicInfo `protobuf:"bytes,1,opt,name=drainage_basic_info,json=drainageBasicInfo,proto3" json:"drainage_basic_info,omitempty"`
	LoadRatio         float64            `protobuf:"fixed64,2,opt,name=load_ratio,json=loadRatio,proto3" json:"load_ratio,omitempty"` // 负载
	FailureStatistics *FailureStatistics `protobuf:"bytes,3,opt,name=failure_statistics,json=failureStatistics,proto3" json:"failure_statistics,omitempty"`
}

func (x *DrainageMetrics) Reset() {
	*x = DrainageMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrainageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainageMetrics) ProtoMessage() {}

func (x *DrainageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainageMetrics.ProtoReflect.Descriptor instead.
func (*DrainageMetrics) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{10}
}

func (x *DrainageMetrics) GetDrainageBasicInfo() *DrainageBasicInfo {
	if x != nil {
		return x.DrainageBasicInfo
	}
	return nil
}

func (x *DrainageMetrics) GetLoadRatio() float64 {
	if x != nil {
		return x.LoadRatio
	}
	return 0
}

func (x *DrainageMetrics) GetFailureStatistics() *FailureStatistics {
	if x != nil {
		return x.FailureStatistics
	}
	return nil
}

// 供水指标
type SupplyMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplyBasicInfo        *SupplyBasicInfo        `protobuf:"bytes,1,opt,name=supply_basic_info,json=supplyBasicInfo,proto3" json:"supply_basic_info,omitempty"`
	SupplyDemandStatistics *SupplyDemandStatistics `protobuf:"bytes,2,opt,name=supply_demand_statistics,json=supplyDemandStatistics,proto3" json:"supply_demand_statistics,omitempty"`
	LoadRatio              float64                 `protobuf:"fixed64,3,opt,name=load_ratio,json=loadRatio,proto3" json:"load_ratio,omitempty"` // 负载
	FailureStatistics      *FailureStatistics      `protobuf:"bytes,4,opt,name=failure_statistics,json=failureStatistics,proto3" json:"failure_statistics,omitempty"`
}

func (x *SupplyMetrics) Reset() {
	*x = SupplyMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_water_output_v1_output_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyMetrics) ProtoMessage() {}

func (x *SupplyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_city_water_output_v1_output_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyMetrics.ProtoReflect.Descriptor instead.
func (*SupplyMetrics) Descriptor() ([]byte, []int) {
	return file_city_water_output_v1_output_proto_rawDescGZIP(), []int{11}
}

func (x *SupplyMetrics) GetSupplyBasicInfo() *SupplyBasicInfo {
	if x != nil {
		return x.SupplyBasicInfo
	}
	return nil
}

func (x *SupplyMetrics) GetSupplyDemandStatistics() *SupplyDemandStatistics {
	if x != nil {
		return x.SupplyDemandStatistics
	}
	return nil
}

func (x *SupplyMetrics) GetLoadRatio() float64 {
	if x != nil {
		return x.LoadRatio
	}
	return 0
}

func (x *SupplyMetrics) GetFailureStatistics() *FailureStatistics {
	if x != nil {
		return x.FailureStatistics
	}
	return nil
}

var File_city_water_output_v1_output_proto protoreflect.FileDescriptor

var file_city_water_output_v1_output_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x69, 0x74, 0x79, 0x2f, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x63, 0x69, 0x74, 0x79, 0x2f,
	0x67, 0x65, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2c, 0x0a, 0x04, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x22, 0x5b,
	0x0a, 0x09, 0x52, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f, 0x6f, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x6f, 0x6e, 0x67,
	0x4c, 0x61, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x22, 0x57, 0x0a, 0x0c, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x64,
	0x65, 0x70, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f, 0x6f, 0x64, 0x52, 0x06, 0x64, 0x65,
	0x70, 0x74, 0x68, 0x73, 0x22, 0x2a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x22, 0x6e, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x66, 0x6c, 0x6f, 0x77,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x9b, 0x01, 0x0a, 0x03, 0x41, 0x6f, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x75, 0x6e, 0x73, 0x61,
	0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64,
	0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x75, 0x6e,
	0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x22, 0xd4,
	0x01, 0x0a, 0x11, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x75, 0x6e, 0x64,
	0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0f, 0x75, 0x6e, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x64, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x25,
	0x0a, 0x0e, 0x66, 0x6c, 0x6f, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x66, 0x6c, 0x6f, 0x6f, 0x64, 0x65, 0x64, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x0f, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0b, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x77,
	0x22, 0xae, 0x02, 0x0a, 0x16, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6d, 0x61, 0x6e,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x44, 0x65, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x13, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65,
	0x64, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x12, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x19, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69,
	0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x17, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66,
	0x69, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x6f, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x61, 0x6f, 0x69, 0x73, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x75, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x5f,
	0x61, 0x6f, 0x69, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x75, 0x6e, 0x73, 0x61,
	0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x41, 0x6f, 0x69, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x75,
	0x6e, 0x73, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x6f, 0x69, 0x73, 0x5f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x75, 0x6e, 0x73,
	0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x41, 0x6f, 0x69, 0x73, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x22, 0x78, 0x0a, 0x11, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x0f,
	0x44, 0x72, 0x61, 0x69, 0x6e, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x57, 0x0a, 0x13, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x61, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x56, 0x0a, 0x12, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x11, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22,
	0xc1, 0x02, 0x0a, 0x0d, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x51, 0x0a, 0x11, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x66, 0x0a, 0x18, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x64,
	0x65, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x16, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6d, 0x61,
	0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x56, 0x0a, 0x12, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x77,
	0x61, 0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x11, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2a, 0x4d, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x49,
	0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x50, 0x45, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x4d, 0x50,
	0x10, 0x02, 0x42, 0xd6, 0x01, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x77, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x42,
	0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x2e, 0x66, 0x69, 0x62, 0x6c, 0x61, 0x62, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x73,
	0x69, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x69, 0x74,
	0x79, 0x2f, 0x77, 0x61, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2f, 0x76,
	0x31, 0x3b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x57, 0x4f,
	0xaa, 0x02, 0x14, 0x43, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x14, 0x43, 0x69, 0x74, 0x79, 0x5c, 0x57,
	0x61, 0x74, 0x65, 0x72, 0x5c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x20, 0x43, 0x69, 0x74, 0x79, 0x5c, 0x57, 0x61, 0x74, 0x65, 0x72, 0x5c, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x17, 0x43, 0x69, 0x74, 0x79, 0x3a, 0x3a, 0x57, 0x61, 0x74, 0x65, 0x72, 0x3a,
	0x3a, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_city_water_output_v1_output_proto_rawDescOnce sync.Once
	file_city_water_output_v1_output_proto_rawDescData = file_city_water_output_v1_output_proto_rawDesc
)

func file_city_water_output_v1_output_proto_rawDescGZIP() []byte {
	file_city_water_output_v1_output_proto_rawDescOnce.Do(func() {
		file_city_water_output_v1_output_proto_rawDescData = protoimpl.X.CompressGZIP(file_city_water_output_v1_output_proto_rawDescData)
	})
	return file_city_water_output_v1_output_proto_rawDescData
}

var file_city_water_output_v1_output_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_city_water_output_v1_output_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_city_water_output_v1_output_proto_goTypes = []interface{}{
	(LinkType)(0),                  // 0: city.water.output.v1.LinkType
	(*Road)(nil),                   // 1: city.water.output.v1.Road
	(*RoadFlood)(nil),              // 2: city.water.output.v1.RoadFlood
	(*DetailedRoad)(nil),           // 3: city.water.output.v1.DetailedRoad
	(*Node)(nil),                   // 4: city.water.output.v1.Node
	(*Link)(nil),                   // 5: city.water.output.v1.Link
	(*Aoi)(nil),                    // 6: city.water.output.v1.Aoi
	(*DrainageBasicInfo)(nil),      // 7: city.water.output.v1.DrainageBasicInfo
	(*SupplyBasicInfo)(nil),        // 8: city.water.output.v1.SupplyBasicInfo
	(*SupplyDemandStatistics)(nil), // 9: city.water.output.v1.SupplyDemandStatistics
	(*FailureStatistics)(nil),      // 10: city.water.output.v1.FailureStatistics
	(*DrainageMetrics)(nil),        // 11: city.water.output.v1.DrainageMetrics
	(*SupplyMetrics)(nil),          // 12: city.water.output.v1.SupplyMetrics
	(*v2.LongLatPosition)(nil),     // 13: city.geo.v2.LongLatPosition
}
var file_city_water_output_v1_output_proto_depIdxs = []int32{
	13, // 0: city.water.output.v1.RoadFlood.position:type_name -> city.geo.v2.LongLatPosition
	2,  // 1: city.water.output.v1.DetailedRoad.depths:type_name -> city.water.output.v1.RoadFlood
	0,  // 2: city.water.output.v1.Link.type:type_name -> city.water.output.v1.LinkType
	7,  // 3: city.water.output.v1.DrainageMetrics.drainage_basic_info:type_name -> city.water.output.v1.DrainageBasicInfo
	10, // 4: city.water.output.v1.DrainageMetrics.failure_statistics:type_name -> city.water.output.v1.FailureStatistics
	8,  // 5: city.water.output.v1.SupplyMetrics.supply_basic_info:type_name -> city.water.output.v1.SupplyBasicInfo
	9,  // 6: city.water.output.v1.SupplyMetrics.supply_demand_statistics:type_name -> city.water.output.v1.SupplyDemandStatistics
	10, // 7: city.water.output.v1.SupplyMetrics.failure_statistics:type_name -> city.water.output.v1.FailureStatistics
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_city_water_output_v1_output_proto_init() }
func file_city_water_output_v1_output_proto_init() {
	if File_city_water_output_v1_output_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_city_water_output_v1_output_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Road); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoadFlood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailedRoad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aoi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrainageBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyDemandStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailureStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrainageMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_water_output_v1_output_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_city_water_output_v1_output_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_city_water_output_v1_output_proto_goTypes,
		DependencyIndexes: file_city_water_output_v1_output_proto_depIdxs,
		EnumInfos:         file_city_water_output_v1_output_proto_enumTypes,
		MessageInfos:      file_city_water_output_v1_output_proto_msgTypes,
	}.Build()
	File_city_water_output_v1_output_proto = out.File
	file_city_water_output_v1_output_proto_rawDesc = nil
	file_city_water_output_v1_output_proto_goTypes = nil
	file_city_water_output_v1_output_proto_depIdxs = nil
}
