// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: city/sync/v1/sync_service.proto

#include "city/sync/v1/sync_service.pb.h"
#include "city/sync/v1/sync_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace city {
namespace sync {
namespace v1 {

static const char* SyncService_method_names[] = {
  "/city.sync.v1.SyncService/SetURL",
  "/city.sync.v1.SyncService/GetURL",
  "/city.sync.v1.SyncService/Step",
};

std::unique_ptr< SyncService::Stub> SyncService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SyncService::Stub> stub(new SyncService::Stub(channel, options));
  return stub;
}

SyncService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetURL_(SyncService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetURL_(SyncService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Step_(SyncService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SyncService::Stub::SetURL(::grpc::ClientContext* context, const ::city::sync::v1::SetURLRequest& request, ::city::sync::v1::SetURLResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::city::sync::v1::SetURLRequest, ::city::sync::v1::SetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetURL_, context, request, response);
}

void SyncService::Stub::async::SetURL(::grpc::ClientContext* context, const ::city::sync::v1::SetURLRequest* request, ::city::sync::v1::SetURLResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::city::sync::v1::SetURLRequest, ::city::sync::v1::SetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetURL_, context, request, response, std::move(f));
}

void SyncService::Stub::async::SetURL(::grpc::ClientContext* context, const ::city::sync::v1::SetURLRequest* request, ::city::sync::v1::SetURLResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetURL_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::SetURLResponse>* SyncService::Stub::PrepareAsyncSetURLRaw(::grpc::ClientContext* context, const ::city::sync::v1::SetURLRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::city::sync::v1::SetURLResponse, ::city::sync::v1::SetURLRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetURL_, context, request);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::SetURLResponse>* SyncService::Stub::AsyncSetURLRaw(::grpc::ClientContext* context, const ::city::sync::v1::SetURLRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetURLRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SyncService::Stub::GetURL(::grpc::ClientContext* context, const ::city::sync::v1::GetURLRequest& request, ::city::sync::v1::GetURLResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::city::sync::v1::GetURLRequest, ::city::sync::v1::GetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetURL_, context, request, response);
}

void SyncService::Stub::async::GetURL(::grpc::ClientContext* context, const ::city::sync::v1::GetURLRequest* request, ::city::sync::v1::GetURLResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::city::sync::v1::GetURLRequest, ::city::sync::v1::GetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetURL_, context, request, response, std::move(f));
}

void SyncService::Stub::async::GetURL(::grpc::ClientContext* context, const ::city::sync::v1::GetURLRequest* request, ::city::sync::v1::GetURLResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetURL_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::GetURLResponse>* SyncService::Stub::PrepareAsyncGetURLRaw(::grpc::ClientContext* context, const ::city::sync::v1::GetURLRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::city::sync::v1::GetURLResponse, ::city::sync::v1::GetURLRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetURL_, context, request);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::GetURLResponse>* SyncService::Stub::AsyncGetURLRaw(::grpc::ClientContext* context, const ::city::sync::v1::GetURLRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetURLRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SyncService::Stub::Step(::grpc::ClientContext* context, const ::city::sync::v1::StepRequest& request, ::city::sync::v1::StepResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::city::sync::v1::StepRequest, ::city::sync::v1::StepResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Step_, context, request, response);
}

void SyncService::Stub::async::Step(::grpc::ClientContext* context, const ::city::sync::v1::StepRequest* request, ::city::sync::v1::StepResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::city::sync::v1::StepRequest, ::city::sync::v1::StepResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, std::move(f));
}

void SyncService::Stub::async::Step(::grpc::ClientContext* context, const ::city::sync::v1::StepRequest* request, ::city::sync::v1::StepResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::StepResponse>* SyncService::Stub::PrepareAsyncStepRaw(::grpc::ClientContext* context, const ::city::sync::v1::StepRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::city::sync::v1::StepResponse, ::city::sync::v1::StepRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Step_, context, request);
}

::grpc::ClientAsyncResponseReader< ::city::sync::v1::StepResponse>* SyncService::Stub::AsyncStepRaw(::grpc::ClientContext* context, const ::city::sync::v1::StepRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStepRaw(context, request, cq);
  result->StartCall();
  return result;
}

SyncService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SyncService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SyncService::Service, ::city::sync::v1::SetURLRequest, ::city::sync::v1::SetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SyncService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::city::sync::v1::SetURLRequest* req,
             ::city::sync::v1::SetURLResponse* resp) {
               return service->SetURL(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SyncService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SyncService::Service, ::city::sync::v1::GetURLRequest, ::city::sync::v1::GetURLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SyncService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::city::sync::v1::GetURLRequest* req,
             ::city::sync::v1::GetURLResponse* resp) {
               return service->GetURL(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SyncService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SyncService::Service, ::city::sync::v1::StepRequest, ::city::sync::v1::StepResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SyncService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::city::sync::v1::StepRequest* req,
             ::city::sync::v1::StepResponse* resp) {
               return service->Step(ctx, req, resp);
             }, this)));
}

SyncService::Service::~Service() {
}

::grpc::Status SyncService::Service::SetURL(::grpc::ServerContext* context, const ::city::sync::v1::SetURLRequest* request, ::city::sync::v1::SetURLResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SyncService::Service::GetURL(::grpc::ServerContext* context, const ::city::sync::v1::GetURLRequest* request, ::city::sync::v1::GetURLResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SyncService::Service::Step(::grpc::ServerContext* context, const ::city::sync::v1::StepRequest* request, ::city::sync::v1::StepResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace city
}  // namespace sync
}  // namespace v1

