// @generated by protoc-gen-es v1.10.0
// @generated from file city/event/v1/event_service.proto (package city.event.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Event } from "./event_pb.js";

/**
 * @generated from message city.event.v1.PublishRequest
 */
export const PublishRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.event.v1.PublishRequest",
  () => [
    { no: 1, name: "event", kind: "message", T: Event },
  ],
);

/**
 * @generated from message city.event.v1.PublishResponse
 */
export const PublishResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.event.v1.PublishResponse",
  [],
);

/**
 * @generated from message city.event.v1.PullRequest
 */
export const PullRequest = /*@__PURE__*/ proto3.makeMessageType(
  "city.event.v1.PullRequest",
  [],
);

/**
 * @generated from message city.event.v1.PullResponse
 */
export const PullResponse = /*@__PURE__*/ proto3.makeMessageType(
  "city.event.v1.PullResponse",
  () => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ],
);

