// @generated by protoc-gen-connect-es v1.2.1
// @generated from file city/clock/v1/clock_service.proto (package city.clock.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NowRequest, NowResponse } from "./clock_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service city.clock.v1.ClockService
 */
export declare const ClockService: {
  readonly typeName: "city.clock.v1.ClockService",
  readonly methods: {
    /**
     * 获取当前的模拟时间
     *
     * @generated from rpc city.clock.v1.ClockService.Now
     */
    readonly now: {
      readonly name: "Now",
      readonly I: typeof NowRequest,
      readonly O: typeof NowResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

